Refactor urls
fga-eps-mds/2023-1-MeasureSoftGram-Service pull request #6
Opened 2023-05-17 19:32 UTC by SwampTG

# Refatoração das URLs

## Descrição

Ao implementar a autorização, verificou-se a necessidade de organizar, as rotas que são construídas de forma recursiva.
Agora, a rota de cada modelo (Organização, Produto e Repositório) cuida de suas URLs.

[#](link_da_issue)

## Critérios de aceitação
(Exemplos de critérios de aceitação)

2023-06-18 14:53 UTC, luisgfmarques requested changes
Por favor, corrija ou comente os pontos apontados e solicite uma nova revisão.

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/organizations.py
> +                    'view': views.ProductViewSet,
Daria para importar diretamente o ProductViewSet para manutenção do padrão com as demais routes que constam no projeto?

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/products.py
> +import organizations.views as views
Aqui novamente, na linha de baixo e realizado o import diretamente da classe, e esse import e realizado o importe do arquivo para depois dar um import da classe(view.Class), e possível manter o mesmo padrão entre os dois imports?

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/repos.py
> +    SupportedMeasureModelViewSet,
Este import não está sendo utilizado.

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/repos.py
> +    SupportedMetricModelViewSet,
Este import não está sendo utilizado.

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/repos.py
> +    SupportedCharacteristicModelViewSet,
Este import não está sendo utilizado.

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/repos.py
> +import organizations.views as views
Este import não está sendo utilizado.

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/repos.py
> +    SupportedSubCharacteristicModelViewSet,
Este import não está sendo utilizado.

2023-06-18 14:53 UTC, luisgfmarques commented on src/organizations/routers/routers.py
> +import organizations.views as views
Este import não está sendo utilizado.

2023-06-21 22:19 UTC, CarlosFiuza approved these changes

2023-06-21 23:52 UTC, luisgfmarques approved these changes

2023-06-22 00:11 UTC, merged